variable "region" {}
variable "ami" {}
variable "instance_type" {}
variable "instance_count" {}
variable "environment" {}
variable "created_by" {}
variable "dept" {}
variable "key_path" {}
variable "ssh_user" {}
variable "script_path" {}
